G_Error	    = "<?error found?>"; 
G_Status	= "<?error status?>"; 
G_Error_Msg	= "<?error message?>";
G_AjaxToken  = "<?echo $var:sys_Token?>";
var G_checkfw_status="<?get :InternetGatewayDevice.X_TWSZ-COM_Lang.X_TWSZ-COM_UpdateStatus?>";
var G_NEWFwMIN = "<?get :InternetGatewayDevice.X_TWSZ-COM_Lang.X_TWSZ-COM_NEWFW_MIN?>";
var G_NEWFwMAJ = "<?get :InternetGatewayDevice.X_TWSZ-COM_Lang.X_TWSZ-COM_NEWFW_MAJ?>";
var G_LatestFwDate = "<?get :InternetGatewayDevice.X_TWSZ-COM_Lang.X_TWSZ-COM_NEWFW_DATE?>";
var G_LatestFwURLS = "<?get :InternetGatewayDevice.X_TWSZ-COM_Lang.X_TWSZ-COM_FW_URLS?>";