include $(ROOTDIR)/.config

subdir-$(CONFIG_TBSMOD_BUTTON) +=button
subdir-$(CONFIG_TBSMOD_LED) +=led


#TBS-TAG: by pengyao 2011-06-16
#DESC: Network Fast Processing Adapter
subdir-${CONFIG_TBS_NFP_ADAPTER} += nfp_adapter
subdir-${CONFIG_TBS_NFP} += tbs_nfp

subdir-y 		 +=product

include $(ROOTDIR)/Rules.make
