
ifeq ($(CONFIG_TCSUPPORT_CPU_MT7510), y)
EXTRA_AFLAGS += -DTCSUPPORT_CPU_MT7510
endif

EXTRA_AFLAGS += -DRALINK_PCIE_ADDR_SWAP=1
EXTRA_AFLAGS += -DTCSUPPORT_HWNAT_WIFI=1
EXTRA_AFLAGS += -DTCPLATFORM=mt7510
EXTRA_AFLAGS += -DTC3262=1
EXTRA_AFLAGS += -DRT63365=1
EXTRA_AFLAGS += -DTCSUPPORT_MT7510_FE=1
EXTRA_AFLAGS += -DTCSUPPORT_ADDR_MAPPING=1
EXTRA_AFLAGS += -DTCSUPPORT_FINAL_DRAMC=1

ifeq ($(strip $(CONFIG_TCSUPPORT_MT7530_EXTERNAL)), y)
EXTRA_AFLAGS += -DMT7530_SUPPORT
endif

ifeq ($(strip $(CONFIG_TCSUPPORT_PRODUCTIONLINE)), y)
EXTRA_AFLAGS += -DTCSUPPORT_PRODUCTIONLINE
endif

ifeq ($(CONFIG_TCSUPPORT_KERNEL), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNEL
endif

ifeq ($(CONFIG_TCSUPPORT_2_6_36_KERNEL), y)
EXTRA_AFLAGS += -DTCSUPPORT_2_6_36_KERNEL
endif

ifeq ($(CONFIG_WAN_ATM), y)
EXTRA_AFLAGS += -DWAN_ATM
endif

ifeq ($(CONFIG_WAN_PTM), y)
EXTRA_AFLAGS += -DWAN_PTM
endif

ifeq ($(CONFIG_WAN_ETHER), y)
EXTRA_AFLAGS += -DWAN_ETHER
endif

ifeq ($(CONFIG_TCSUPPORT_WAN_ATM), y)
EXTRA_AFLAGS += -DTCSUPPORT_WAN_ATM
endif

ifeq ($(CONFIG_TCSUPPORT_WAN_PTM), y)
EXTRA_AFLAGS += -DTCSUPPORT_WAN_PTM
endif

ifeq ($(CONFIG_TCSUPPORT_WAN_ETHER), y)
EXTRA_AFLAGS += -DTCSUPPORT_WAN_ETHER
endif

ifeq ($(CONFIG_TCSUPPORT_SDRAM_8M), y)
EXTRA_AFLAGS += -DTCSUPPORT_SDRAM_8M
endif

ifeq ($(CONFIG_TCSUPPORT_SDRAM_16M), y)
EXTRA_AFLAGS += -DTCSUPPORT_SDRAM_16M
endif

ifeq ($(CONFIG_TCSUPPORT_SDRAM_32M), y)
EXTRA_AFLAGS += -DTCSUPPORT_SDRAM_32M
endif

ifeq ($(CONFIG_TCSUPPORT_SDRAM_64M), y)
EXTRA_AFLAGS += -DTCSUPPORT_SDRAM_64M
endif

ifeq ($(CONFIG_TCSUPPORT_BOOT_LZMA), y)
EXTRA_AFLAGS += -DTCSUPPORT_BOOT_LZMA
endif

ifeq ($(CONFIG_TCSUPPORT_BB_SPI), y)
EXTRA_AFLAGS += -DTCSUPPORT_BB_SPI
endif

ifeq ($(CONFIG_TCSUPPORT_BB_NAND), y)
EXTRA_AFLAGS += -DTCSUPPORT_BB_NAND
endif

ifeq ($(CONFIG_TCSUPPORT_DDR_CALI), y)
EXTRA_AFLAGS += -DTCSUPPORT_DDR_CALI
endif

ifeq ($(CONFIG_TCSUPPORT_BOOTROM_LARGE_SIZE), y)
EXTRA_AFLAGS += -DTCSUPPORT_BOOTROM_LARGE_SIZE
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_AUTO), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_AUTO
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_TC3162), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_TC3162
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_TC3162_PB), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_TC3162_PB
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_TC3162_VOIP), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_TC3162_VOIP
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_TC3162_IPv6), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_TC3162_IPv6
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_TC3162U), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_TC3162U
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_TC3162U_IPv6), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_TC3162U_IPv6
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_TC3262), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_TC3262
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_TC3182), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_TC3182
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_RT63165), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_RT63165
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_RT63365), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_RT63365
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_RT65168), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_RT65168
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_MT7510), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_MT7510
endif

ifeq ($(CONFIG_TCSUPPORT_KERNELCONFIG_MT7520), y)
EXTRA_AFLAGS += -DTCSUPPORT_KERNELCONFIG_MT7520
endif

ifeq ($(CONFIG_TCSUPPORT_BUSYBOXCONFIG_AUTO), y)
EXTRA_AFLAGS += -DTCSUPPORT_BUSYBOXCONFIG_AUTO
endif

ifeq ($(CONFIG_TCSUPPORT_BUSYBOXCONFIG_TC3162), y)
EXTRA_AFLAGS += -DTCSUPPORT_BUSYBOXCONFIG_TC3162
endif

ifeq ($(CONFIG_TCSUPPORT_BUSYBOXCONFIG_TC3162_PB), y)
EXTRA_AFLAGS += -DTCSUPPORT_BUSYBOXCONFIG_TC3162_PB
endif

ifeq ($(CONFIG_TCSUPPORT_BUSYBOXCONFIG_TC3162_IPv6), y)
EXTRA_AFLAGS += -DTCSUPPORT_BUSYBOXCONFIG_TC3162_IPv6
endif

ifeq ($(CONFIG_TCSUPPORT_BUSYBOXCONFIG_TC3162U), y)
EXTRA_AFLAGS += -DTCSUPPORT_BUSYBOXCONFIG_TC3162U
endif

ifeq ($(CONFIG_TCSUPPORT_BUSYBOXCONFIG_TC3162U_IPv6), y)
EXTRA_AFLAGS += -DTCSUPPORT_BUSYBOXCONFIG_TC3162U_IPv6
endif

ifeq ($(CONFIG_TCSUPPORT_BUSYBOXCONFIG_TC3262), y)
EXTRA_AFLAGS += -DTCSUPPORT_BUSYBOXCONFIG_TC3262
endif

ifeq ($(CONFIG_TCSUPPORT_DMT_3085), y)
EXTRA_AFLAGS += -DTCSUPPORT_DMT_3085
endif

ifeq ($(CONFIG_TCSUPPORT_DMT_3086), y)
EXTRA_AFLAGS += -DTCSUPPORT_DMT_3086
endif

ifeq ($(CONFIG_TCSUPPORT_DMT_3087), y)
EXTRA_AFLAGS += -DTCSUPPORT_DMT_3087
endif

ifeq ($(CONFIG_TCSUPPORT_DMT_3095), y)
EXTRA_AFLAGS += -DTCSUPPORT_DMT_3095
endif

ifeq ($(CONFIG_TCSUPPORT_DUAL_IMAGE), y)
EXTRA_AFLAGS += -DTCSUPPORT_DUAL_IMAGE
endif

ifeq ($(CONFIG_TCSUPPORT_TR68LED), y)
EXTRA_AFLAGS += -DTCSUPPORT_TR68LED
endif

ifeq ($(CONFIG_TCSUPPORT_GPIO_ECM), y)
EXTRA_AFLAGS += -DTCSUPPORT_GPIO_ECM
endif

ifeq ($(CONFIG_TCSUPPORT_I2C), y)
EXTRA_AFLAGS += -DTCSUPPORT_I2C
endif

ifeq ($(CONFIG_TCSUPPORT_LEDKEY), y)
EXTRA_AFLAGS += -DTCSUPPORT_LEDKEY
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN
TCSUPPORT_WLAN=y
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_8021X), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_8021X
TCSUPPORT_WLAN_8021X=y
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_8021X_EXT), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_8021X_EXT
TCSUPPORT_WLAN_8021X_EXT=y
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_8021X_EXT_SHOW_MAC), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_8021X_EXT_SHOW_MAC
TCSUPPORT_WLAN_8021X_EXT_SHOW_MAC=y
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_WPS), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_WPS
TCSUPPORT_WLAN_WPS=y
endif
ifeq ($(CONFIG_TCSUPPORT_WLAN_WPS_V2), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_WPS_V2
TCSUPPORT_WLAN_WPS_V2=y
endif
ifeq ($(CONFIG_TCSUPPORT_WLAN_WDS), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_WDS
TCSUPPORT_WLAN_WDS=y
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_IGMPSNOOP), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_IGMPSNOOP
TCSUPPORT_WLAN_IGMPSNOOP=y
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_ATE), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_ATE
TCSUPPORT_WLAN_ATE=y
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_QATOOL), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_QATOOL
TCSUPPORT_WLAN_ATE=y
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_WPS_LEDSPEC), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_WPS_LEDSPEC
TCSUPPORT_WLAN_WPS_LEDSPEC=y
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_GPIO), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_GPIO
TCSUPPORT_WLAN_8021X_EXT=y
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_RT2561), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_RT2561
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_RT3390), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_RT3390
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_RT5392), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_RT5392
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_RT5390), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_RT5390
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_RT5390HL), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_RT5390HL
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_RT3090), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_RT3090
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_MULTIDRIVER), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_MULTIDRIVER
endif

ifeq ($(CONFIG_TCSUPPORT_NODUAL_BAND), y)
EXTRA_AFLAGS += -DTCSUPPORT_NODUAL_BAND
endif

ifeq ($(CONFIG_TCSUPPORT_DUAL_WLAN_RT5592_RT3593), y)
EXTRA_AFLAGS += -DTCSUPPORT_DUAL_WLAN_RT5592_RT3593
TCSUPPORT_DUAL_WLAN_RT5592_RT3593=y
endif

ifeq ($(CONFIG_TCSUPPORT_DUAL_WLAN_RT5592), y)
EXTRA_AFLAGS += -DTCSUPPORT_DUAL_WLAN_RT5592
TCSUPPORT_DUAL_WLAN_RT5592=y
endif

ifeq ($(CONFIG_TCSUPPORT_VPN), y)
EXTRA_AFLAGS += -DTCSUPPORT_VPN
endif

ifeq ($(CONFIG_TCSUPPORT_HW_CRYPTO), y)
EXTRA_AFLAGS += -DTCSUPPORT_HW_CRYPTO
endif

ifeq ($(CONFIG_TCSUPPORT_EIP93_VERIFY), y)
EXTRA_AFLAGS += -DTCSUPPORT_EIP93_VERIFY
endif

ifeq ($(CONFIG_TCSUPPORT_USBHOST), y)
EXTRA_AFLAGS += -DTCSUPPORT_USBHOST
endif

ifeq ($(CONFIG_TCSUPPORT_USB_NTFS), y)
EXTRA_AFLAGS += -DTCSUPPORT_USB_NTFS
endif

ifeq ($(CONFIG_TCSUPPORT_USB_AUTOMOUNT), y)
EXTRA_AFLAGS += -DTCSUPPORT_USB_AUTOMOUNT
endif

ifeq ($(CONFIG_TCSUPPORT_USB_PRINTER_SERVER), y)
EXTRA_AFLAGS += -DTCSUPPORT_USB_PRINTER_SERVER
endif

ifeq ($(CONFIG_TCSUPPORT_USB_3G_DONGLE), y)
EXTRA_AFLAGS += -DTCSUPPORT_USB_3G_DONGLE
endif

ifeq ($(CONFIG_TCSUPPORT_USB_CAMERA), y)
EXTRA_AFLAGS += -DTCSUPPORT_USB_CAMERA
endif

ifeq ($(CONFIG_TCSUPPORT_USB_HOST_LED), y)
EXTRA_AFLAGS += -DTCSUPPORT_USB_HOST_LED
endif

ifeq ($(CONFIG_TCSUPPORT_CMDAPI), y)
EXTRA_AFLAGS += -DTCSUPPORT_CMDAPI
endif

ifeq ($(CONFIG_TCSUPPORT_AUTOBENCH), y)
EXTRA_AFLAGS += -DTCSUPPORT_AUTOBENCH
endif

ifeq ($(CONFIG_TCSUPPORT_NAND_FLASH), y)
EXTRA_AFLAGS += -DTCSUPPORT_NAND_FLASH
endif

ifeq ($(CONFIG_TCSUPPORT_NAND_BMT), y)
EXTRA_AFLAGS += -DTCSUPPORT_NAND_BMT
endif

ifeq ($(CONFIG_TCSUPPORT_RA_HWNAT), y)
EXTRA_AFLAGS += -DTCSUPPORT_RA_HWNAT
endif

ifeq ($(CONFIG_TCSUPPORT_RA_HWNAT_ENHANCE_HOOK), y)
EXTRA_AFLAGS += -DTCSUPPORT_RA_HWNAT_ENHANCE_HOOK
endif

ifeq ($(CONFIG_TCSUPPORT_DYING_GASP), y)
EXTRA_AFLAGS += -DTCSUPPORT_DYING_GASP
endif

ifeq ($(CONFIG_TCSUPPORT_QDMA_BUFMGR), y)
EXTRA_AFLAGS += -DTCSUPPORT_QDMA_BUFMGR
endif

ifeq ($(CONFIG_TCSUPPORT_MT7530_EXTERNAL), y)
EXTRA_AFLAGS += -DTCSUPPORT_MT7530_EXTERNAL
endif

ifeq ($(CONFIG_TCSUPPORT_SIM_CONTROLLER), y)
EXTRA_AFLAGS += -DTCSUPPORT_SIM_CONTROLLER
endif

ifeq ($(CONFIG_TCSUPPORT_IPV6), y)
EXTRA_AFLAGS += -DTCSUPPORT_IPV6
endif

ifeq ($(CONFIG_TCSUPPORT_IPV6_ENHANCEMENT), y)
EXTRA_AFLAGS += -DTCSUPPORT_IPV6_ENHANCEMENT
endif

ifeq ($(CONFIG_TCSUPPORT_DSLITE), y)
EXTRA_AFLAGS += -DTCSUPPORT_DSLITE
endif

ifeq ($(CONFIG_TCSUPPORT_6RD), y)
EXTRA_AFLAGS += -DTCSUPPORT_6RD
endif

ifeq ($(CONFIG_TCSUPPORT_OPT212), y)
EXTRA_AFLAGS += -DTCSUPPORT_OPT212
endif

ifeq ($(CONFIG_TCSUPPORT_IPV6_ADVANCE), y)
EXTRA_AFLAGS += -DTCSUPPORT_IPV6_ADVANCE
endif

ifeq ($(CONFIG_TCSUPPORT_IPV6_ACL), y)
EXTRA_AFLAGS += -DTCSUPPORT_IPV6_ACL
endif

ifeq ($(CONFIG_TCSUPPORT_IPV6_FIREWALL), y)
EXTRA_AFLAGS += -DTCSUPPORT_IPV6_FIREWALL
endif

ifeq ($(CONFIG_TCSUPPORT_IPV6_FIREWALL_RFC2827), y)
EXTRA_AFLAGS += -DTCSUPPORT_IPV6_FIREWALL_RFC2827
endif

ifeq ($(CONFIG_TCSUPPORT_IPV6_TELNET), y)
EXTRA_AFLAGS += -DTCSUPPORT_IPV6_TELNET
endif

ifeq ($(CONFIG_TCSUPPORT_IPV6_TFTP), y)
EXTRA_AFLAGS += -DTCSUPPORT_IPV6_TFTP
endif

ifeq ($(CONFIG_TCSUPPORT_IPV6_FTP), y)
EXTRA_AFLAGS += -DTCSUPPORT_IPV6_FTP
endif

ifeq ($(CONFIG_TCSUPPORT_IPV6_INETD), y)
EXTRA_AFLAGS += -DTCSUPPORT_IPV6_INETD
endif

ifeq ($(CONFIG_TCSUPPORT_IPV6_PRIVACYADDRS), y)
EXTRA_AFLAGS += -DTCSUPPORT_IPV6_PRIVACYADDRS
endif

ifeq ($(CONFIG_TCSUPPORT_IPV6_STATIC_ROUTE), y)
EXTRA_AFLAGS += -DTCSUPPORT_IPV6_STATIC_ROUTE
endif

ifeq ($(CONFIG_TCSUPPORT_CWMP), y)
EXTRA_AFLAGS += -DTCSUPPORT_CWMP
endif

ifeq ($(CONFIG_TCSUPPORT_CWMP_CRPORTCHANGE), y)
EXTRA_AFLAGS += -DTCSUPPORT_CWMP_CRPORTCHANGE
endif

ifeq ($(CONFIG_TCSUPPORT_CWMP_PRECISE_TIME), y)
EXTRA_AFLAGS += -DTCSUPPORT_CWMP_PRECISE_TIME
endif

ifeq ($(CONFIG_TCSUPPORT_CWMP_FAST_GET), y)
EXTRA_AFLAGS += -DTCSUPPORT_CWMP_FAST_GET
endif

ifeq ($(CONFIG_TCSUPPORT_RANDOM_INFORM), y)
EXTRA_AFLAGS += -DTCSUPPORT_RANDOM_INFORM
endif

ifeq ($(CONFIG_TCSUPPORT_TRACEROUTE), y)
EXTRA_AFLAGS += -DTCSUPPORT_TRACEROUTE
endif

ifeq ($(CONFIG_TCSUPPORT_CWMP_VDSL), y)
EXTRA_AFLAGS += -DTCSUPPORT_CWMP_VDSL
endif

ifeq ($(CONFIG_TCSUPPORT_CWMP_ACL), y)
EXTRA_AFLAGS += -DTCSUPPORT_CWMP_ACL
endif

ifeq ($(CONFIG_TCSUPPORT_DOWNSTREAM_QOS), y)
EXTRA_AFLAGS += -DTCSUPPORT_DOWNSTREAM_QOS
endif

ifeq ($(CONFIG_TCSUPPORT_QOS), y)
EXTRA_AFLAGS += -DTCSUPPORT_QOS
endif

ifeq ($(CONFIG_TCSUPPORT_IGMP_QOS), y)
EXTRA_AFLAGS += -DTCSUPPORT_IGMP_QOS
endif

ifeq ($(CONFIG_TCSUPPORT_PORTBIND), y)
EXTRA_AFLAGS += -DTCSUPPORT_PORTBIND
endif

ifeq ($(CONFIG_TCSUPPORT_VLAN_TAG), y)
EXTRA_AFLAGS += -DTCSUPPORT_VLAN_TAG
endif

ifeq ($(CONFIG_TCSUPPORT_CWMP_SSL), y)
EXTRA_AFLAGS += -DTCSUPPORT_CWMP_SSL
endif

ifeq ($(CONFIG_TCSUPPORT_CWMP_SSL_MULTICA), y)
EXTRA_AFLAGS += -DTCSUPPORT_CWMP_SSL_MULTICA
endif

ifeq ($(CONFIG_TCSUPPORT_CWMP_TR111), y)
EXTRA_AFLAGS += -DTCSUPPORT_CWMP_TR111
endif

ifeq ($(CONFIG_TCSUPPORT_CWMP_TR143), y)
EXTRA_AFLAGS += -DTCSUPPORT_CWMP_TR143
endif

ifeq ($(CONFIG_TCSUPPORT_WEBSERVER_SSL), y)
EXTRA_AFLAGS += -DTCSUPPORT_WEBSERVER_SSL
endif

ifeq ($(CONFIG_TCSUPPORT_SSH), y)
EXTRA_AFLAGS += -DTCSUPPORT_SSH
endif

ifeq ($(CONFIG_TCSUPPORT_SNMP), y)
EXTRA_AFLAGS += -DTCSUPPORT_SNMP
endif

ifeq ($(CONFIG_TCSUPPORT_SNMP_FULL), y)
EXTRA_AFLAGS += -DTCSUPPORT_SNMP_FULL
endif

ifeq ($(CONFIG_TCSUPPORT_START_TRAP), y)
EXTRA_AFLAGS += -DTCSUPPORT_START_TRAP
endif

ifeq ($(CONFIG_TCSUPPORT_SNMP_CHT), y)
EXTRA_AFLAGS += -DTCSUPPORT_SNMP_CHT
endif

ifeq ($(CONFIG_TCSUPPORT_SNMP_V3), y)
EXTRA_AFLAGS += -DTCSUPPORT_SNMP_V3
endif

ifeq ($(CONFIG_TCSUPPORT_IPV6_SNMP), y)
EXTRA_AFLAGS += -DTCSUPPORT_IPV6_SNMP
endif

ifeq ($(CONFIG_TCSUPPORT_SNMP_REDUCED), y)
EXTRA_AFLAGS += -DTCSUPPORT_SNMP_REDUCED
endif

ifeq ($(CONFIG_TCSUPPORT_SNMP_TRUSTIP), y)
EXTRA_AFLAGS += -DTCSUPPORT_SNMP_TRUSTIP
endif

ifeq ($(CONFIG_TCSUPPORT_SNMP_ATMADSL), y)
EXTRA_AFLAGS += -DTCSUPPORT_SNMP_ATMADSL
endif

ifeq ($(CONFIG_TCSUPPORT_ALIASIP), y)
EXTRA_AFLAGS += -DTCSUPPORT_ALIASIP
endif

ifeq ($(CONFIG_TCSUPPORT_DHCP_STATIC), y)
EXTRA_AFLAGS += -DTCSUPPORT_DHCP_STATIC
endif

ifeq ($(CONFIG_TCSUPPORT_DHCP_PROFILE), y)
EXTRA_AFLAGS += -DTCSUPPORT_DHCP_PROFILE
endif

ifeq ($(CONFIG_TCSUPPORT_E8B), y)
EXTRA_AFLAGS += -DTCSUPPORT_E8B
endif

ifeq ($(CONFIG_TCSUPPORT_DNSEACHPVC), y)
EXTRA_AFLAGS += -DTCSUPPORT_DNSEACHPVC
endif

ifeq ($(CONFIG_TCSUPPORT_MLD_SNOOPING), y)
EXTRA_AFLAGS += -DTCSUPPORT_MLD_SNOOPING
endif

ifeq ($(CONFIG_TCSUPPORT_MLD_PROXY), y)
EXTRA_AFLAGS += -DTCSUPPORT_MLD_PROXY
endif

ifeq ($(CONFIG_TCSUPPORT_IGMP_PROXY_V3), y)
EXTRA_AFLAGS += -DTCSUPPORT_IGMP_PROXY_V3
endif

ifeq ($(CONFIG_TCSUPPORT_IGMP_SNOOPING), y)
EXTRA_AFLAGS += -DTCSUPPORT_IGMP_SNOOPING
endif

ifeq ($(CONFIG_TCSUPPORT_IGMPSNOOPING_ENHANCE), y)
EXTRA_AFLAGS += -DTCSUPPORT_IGMPSNOOPING_ENHANCE
endif

ifeq ($(CONFIG_TCSUPPORT_IGMP_SNOOPING_V3), y)
EXTRA_AFLAGS += -DTCSUPPORT_IGMP_SNOOPING_V3
endif

ifeq ($(CONFIG_TCSUPPORT_SMUX), y)
EXTRA_AFLAGS += -DTCSUPPORT_SMUX
endif

ifeq ($(CONFIG_TCSUPPORT_MTD_ENCHANCEMENT), y)
EXTRA_AFLAGS += -DTCSUPPORT_MTD_ENCHANCEMENT
endif

ifeq ($(CONFIG_TCSUPPORT_RESERVEAREA_BLOCK=4), y)
EXTRA_AFLAGS += -DTCSUPPORT_RESERVEAREA_BLOCK=4
endif

ifeq ($(CONFIG_TCSUPPORT_BACKUPROMFILE), y)
EXTRA_AFLAGS += -DTCSUPPORT_BACKUPROMFILE
endif

ifeq ($(CONFIG_TCSUPPORT_NOTDEFAULTROMFILEAREA), y)
EXTRA_AFLAGS += -DTCSUPPORT_NOTDEFAULTROMFILEAREA
endif

ifeq ($(CONFIG_TCSUPPORT_CT_2PWIFI), y)
EXTRA_AFLAGS += -DTCSUPPORT_CT_2PWIFI
endif

ifeq ($(CONFIG_TCSUPPORT_PRODUCTIONLINE), y)
EXTRA_AFLAGS += -DTCSUPPORT_PRODUCTIONLINE
endif

ifeq ($(CONFIG_TCSUPPORT_SYSLOG), y)
EXTRA_AFLAGS += -DTCSUPPORT_SYSLOG
endif

ifeq ($(CONFIG_TCSUPPORT_SYSLOG_ENHANCE), y)
EXTRA_AFLAGS += -DTCSUPPORT_SYSLOG_ENHANCE
endif

ifeq ($(CONFIG_TCSUPPORT_REMOTE_SYSLOG), y)
EXTRA_AFLAGS += -DTCSUPPORT_REMOTE_SYSLOG
endif

ifeq ($(CONFIG_TCSUPPORT_AUTO_IP), y)
EXTRA_AFLAGS += -DTCSUPPORT_AUTO_IP
endif

ifeq ($(CONFIG_TCSUPPORT_DMS), y)
EXTRA_AFLAGS += -DTCSUPPORT_DMS
endif

ifeq ($(CONFIG_TCSUPPORT_DMS_FULL_FORMAT), y)
EXTRA_AFLAGS += -DTCSUPPORT_DMS_FULL_FORMAT
endif

ifeq ($(CONFIG_TCSUPPORT_WEB_SAVE), y)
EXTRA_AFLAGS += -DTCSUPPORT_WEB_SAVE
endif

ifeq ($(CONFIG_TCSUPPORT_FW_UPGRADE_16M), y)
EXTRA_AFLAGS += -DTCSUPPORT_FW_UPGRADE_16M
endif

ifeq ($(CONFIG_TCSUPPORT_BRIDGE_FASTPATH), y)
EXTRA_AFLAGS += -DTCSUPPORT_BRIDGE_FASTPATH
endif

ifeq ($(CONFIG_RA_PARENTALCONTROL), y)
EXTRA_AFLAGS += -DRA_PARENTALCONTROL
endif

ifeq ($(CONFIG_TCSUPPORT_PARENTAL_URLBLOCK), y)
EXTRA_AFLAGS += -DTCSUPPORT_PARENTAL_URLBLOCK
endif

ifeq ($(CONFIG_TCSUPPORT_SIPROXD), y)
EXTRA_AFLAGS += -DTCSUPPORT_SIPROXD
endif

ifeq ($(CONFIG_TCSUPPORT_SAMBA_NONE), y)
EXTRA_AFLAGS += -DTCSUPPORT_SAMBA_NONE
endif

ifeq ($(CONFIG_TCSUPPORT_SAMBA), y)
EXTRA_AFLAGS += -DTCSUPPORT_SAMBA
endif

ifeq ($(CONFIG_TCSUPPORT_SAMBA_IPv6), y)
EXTRA_AFLAGS += -DTCSUPPORT_SAMBA_IPv6
endif

ifeq ($(CONFIG_TCSUPPORT_CODE_SHRINK), y)
EXTRA_AFLAGS += -DTCSUPPORT_CODE_SHRINK
endif

ifeq ($(CONFIG_RA_ETHERMEDIATYPE), y)
EXTRA_AFLAGS += -DRA_ETHERMEDIATYPE
endif

ifeq ($(CONFIG_TCSUPPORT_MODEL_CHECK), y)
EXTRA_AFLAGS += -DTCSUPPORT_MODEL_CHECK
endif

ifeq ($(CONFIG_TCSUPPORT_PORT_TRIGGER), y)
EXTRA_AFLAGS += -DTCSUPPORT_PORT_TRIGGER
endif

ifeq ($(CONFIG_TCSUPPORT_RA_GUI), y)
EXTRA_AFLAGS += -DTCSUPPORT_RA_GUI
endif

ifeq ($(CONFIG_TCSUPPORT_FILTER_DSCP), y)
EXTRA_AFLAGS += -DTCSUPPORT_FILTER_DSCP
endif

ifeq ($(CONFIG_TCSUPPORT_DHCP_PORT_FLT), y)
EXTRA_AFLAGS += -DTCSUPPORT_DHCP_PORT_FLT
endif

ifeq ($(CONFIG_TCSUPPORT_1NTP_SERVER), y)
EXTRA_AFLAGS += -DTCSUPPORT_1NTP_SERVER
endif

ifeq ($(CONFIG_TCSUPPORT_2NTP_SERVER), y)
EXTRA_AFLAGS += -DTCSUPPORT_2NTP_SERVER
endif

ifeq ($(CONFIG_TCSUPPORT_3NTP_SERVER), y)
EXTRA_AFLAGS += -DTCSUPPORT_3NTP_SERVER
endif

ifeq ($(CONFIG_TCSUPPORT_UPNP_CERT), y)
EXTRA_AFLAGS += -DTCSUPPORT_UPNP_CERT
endif

ifeq ($(CONFIG_TCSUPPORT_PPP_AUTHEN), y)
EXTRA_AFLAGS += -DTCSUPPORT_PPP_AUTHEN
endif

ifeq ($(CONFIG_TCSUPPORT_TFTP_UPGRADE_PROTECT), y)
EXTRA_AFLAGS += -DTCSUPPORT_TFTP_UPGRADE_PROTECT
endif

ifeq ($(CONFIG_TCSUPPORT_TR069_OPT43), y)
EXTRA_AFLAGS += -DTCSUPPORT_TR069_OPT43
endif

ifeq ($(CONFIG_TCSUPPORT_GENERAL_MULTILANGUAGE), y)
EXTRA_AFLAGS += -DTCSUPPORT_GENERAL_MULTILANGUAGE
endif

ifeq ($(CONFIG_TCSUPPORT_MODEL_NAME_CUSKIT), y)
EXTRA_AFLAGS += -DTCSUPPORT_MODEL_NAME_CUSKIT
endif

ifeq ($(CONFIG_TCSUPPORT_MEMORY_CONTROL), y)
EXTRA_AFLAGS += -DTCSUPPORT_MEMORY_CONTROL
endif

ifeq ($(CONFIG_TCSUPPORT_OOM_RB_NEXT), y)
EXTRA_AFLAGS += -DTCSUPPORT_OOM_RB_NEXT
endif

ifeq ($(CONFIG_TCSUPPORT_SBTHROUGHPUT_ENHANCE), y)
EXTRA_AFLAGS += -DTCSUPPORT_SBTHROUGHPUT_ENHANCE
endif

ifeq ($(CONFIG_TCSUPPORT_VPN_SWITCH_GUI), y)
EXTRA_AFLAGS += -DTCSUPPORT_VPN_SWITCH_GUI
endif

ifeq ($(CONFIG_TCSUPPORT_LAYER3FORWARD_ENHANCEMENT), y)
EXTRA_AFLAGS += -DTCSUPPORT_LAYER3FORWARD_ENHANCEMENT
endif

ifeq ($(CONFIG_TCSUPPORT_UPGRADE_WDOGREBOOT), y)
EXTRA_AFLAGS += -DTCSUPPORT_UPGRADE_WDOGREBOOT
endif

ifeq ($(CONFIG_TCSUPPORT_LED_BTN_CHECK), y)
EXTRA_AFLAGS += -DTCSUPPORT_LED_BTN_CHECK
endif

ifeq ($(CONFIG_TCSUPPORT_WPA_SUPPLICANT), y)
EXTRA_AFLAGS += -DTCSUPPORT_WPA_SUPPLICANT
endif

ifeq ($(CONFIG_TCSUPPORT_SUPPORT_FLASH), y)
EXTRA_AFLAGS += -DTCSUPPORT_SUPPORT_FLASH
endif

ifeq ($(CONFIG_TCSUPPORT_TEST_LED_ALL), y)
EXTRA_AFLAGS += -DTCSUPPORT_TEST_LED_ALL
endif

ifeq ($(CONFIG_TCSUPPORT_CMDPROMPT), y)
EXTRA_AFLAGS += -DTCSUPPORT_CMDPROMPT
endif

ifeq ($(CONFIG_TCSUPPORT_WLAN_MAXSTANUM_GUI), y)
EXTRA_AFLAGS += -DTCSUPPORT_WLAN_MAXSTANUM_GUI
TCSUPPORT_WLAN_MAXSTANUM_GUI=y
endif

ifeq ($(CONFIG_TCSUPPORT_MULTISERVICE_ON_WAN), y)
EXTRA_AFLAGS += -DTCSUPPORT_MULTISERVICE_ON_WAN
endif

ifeq ($(CONFIG_TCSUPPORT_AGEOUT_MAC), y)
EXTRA_AFLAGS += -DTCSUPPORT_AGEOUT_MAC
TCSUPPORT_AGEOUT_MAC=y
endif

ifeq ($(CONFIG_TCSUPPORT_FON), y)
EXTRA_AFLAGS += -DTCSUPPORT_FON
endif

ifeq ($(CONFIG_TCSUPPORT_TR069_UPGRADE_CUSTOM), y)
EXTRA_AFLAGS += -DTCSUPPORT_TR069_UPGRADE_CUSTOM
endif

ifeq ($(CONFIG_TCSUPPORT_MULTI_UPGRADE_LIONS), y)
EXTRA_AFLAGS += -DTCSUPPORT_MULTI_UPGRADE_LIONS
endif

ifeq ($(CONFIG_TCSUPPORT_DUAL_WLAN_RT5592),y)
EXTRA_AFLAGS += -DTCSUPPORT_DUAL_WLAN
TCSUPPORT_DUAL_WLAN=y
endif

ifeq ($(CONFIG_TCSUPPORT_ETHER_ALL_LED), y)
EXTRA_AFLAGS += -DTCSUPPORT_ETHER_ALL_LED
endif

ifeq ($(CONFIG_TCSUPPORT_FW_INTERNET_LED), y)
EXTRA_AFLAGS += -DTCSUPPORT_FW_INTERNET_LED
endif

ifeq ($(CONFIG_TCSUPPORT_VLAN_DOT1P), y)
EXTRA_AFLAGS += -DTCSUPPORT_VLAN_DOT1P
endif

ifeq ($(CONFIG_TCSUPPORT_BONDING), y)
EXTRA_AFLAGS += -DTCSUPPORT_BONDING
endif

ifeq ($(CONFIG_TCSUPPORT_DUAL_WLAN_RT5592_RT3593),y)
EXTRA_AFLAGS += -DTCSUPPORT_DUAL_WLAN -DRT5392 -DBBUTOWBU
TCSUPPORT_DUAL_WLAN=y
endif

ifeq ($(CONFIG_TCSUPPORT_WAN_ETHER_LED), y)
EXTRA_AFLAGS += -DTCSUPPORT_WAN_ETHER_LED
endif

ifeq ($(CONFIG_TCSUPPORT_FTP_CMD), y)
EXTRA_AFLAGS += -DTCSUPPORT_FTP_CMD
endif

ifeq ($(CONFIG_TCSUPPORT_CWMP_FAULT_RESPONSE), y)
EXTRA_AFLAGS += -DTCSUPPORT_CWMP_FAULT_RESPONSE
endif

ifeq ($(CONFIG_TCSUPPORT_DHCP_NOFORWARD), y)
EXTRA_AFLAGS += -DTCSUPPORT_DHCP_NOFORWARD
endif

ifeq ($(CONFIG_TCSUPPORT_WPS_BTN_NEWSPEC), y)
EXTRA_AFLAGS += -DTCSUPPORT_WPS_BTN_NEWSPEC
endif

ifeq ($(CONFIG_TCSUPPORT_MANUAL_ETHERNET_PORTMAP), y)
EXTRA_AFLAGS += -DTCSUPPORT_MANUAL_ETHERNET_PORTMAP
endif

ifeq ($(CONFIG_TCSUPPORT_GUI_ALG_CONTROL), y)
EXTRA_AFLAGS += -DTCSUPPORT_GUI_ALG_CONTROL
endif

ifeq ($(CONFIG_TCSUPPORT_RELEASED_CODE), y)
EXTRA_AFLAGS += -DTCSUPPORT_RELEASED_CODE
endif

ifeq ($(CONFIG_TC_RELEASE_2_6_36_KERNEL), y)
EXTRA_AFLAGS += -DTC_RELEASE_2_6_36_KERNEL
endif
