
# LED Core
obj-$(CONFIG_TBS_LED)	+= led-core.o

# LED Triggers
obj-$(CONFIG_LED_TRIGGER_ON)				+= ledtrig-on.o
obj-$(CONFIG_LED_TRIGGER_OFF)				+= ledtrig-off.o
obj-$(CONFIG_LED_TRIGGER_FLASH)				+= ledtrig-flash.o
obj-$(CONFIG_LED_TRIGGER_FLASH_4HZ)			+= ledtrig-flash-4hz.o
obj-$(CONFIG_LED_TRIGGER_DATAFLASH)			+= ledtrig-dataflash.o
obj-$(CONFIG_LED_TRIGGER_WPS_INPROGRESS)	+= ledtrig-wps_inprogress.o
obj-$(CONFIG_LED_TRIGGER_WPS_ERROR)			+= ledtrig-wps_error.o
obj-$(CONFIG_LED_TRIGGER_WPS_OVERLAP)		+= ledtrig-wps_overlap.o
obj-$(CONFIG_LED_TRIGGER_WPS_SUCCESS)		+= ledtrig-wps_success.o

# LED Device
obj-$(CONFIG_LED_AR7130)	+= led_ar7130.o
obj-$(CONFIG_LED_AMAZON_SE)	+= led_amazon_se.o
obj-$(CONFIG_LED_RT3052)	+= led_rt3052.o 
obj-$(CONFIG_LED_VX180)		+= led_vx180.o
obj-$(CONFIG_LED_RTL8672)	+= led_rtl8672.o
obj-$(CONFIG_LED_RTL8196C)	+= led_rtl8196c.o
obj-$(CONFIG_LED_RTL8196E)	+= led_rtl8196e.o
obj-$(CONFIG_LED_RTL8197D)	+= led_rtl8197d.o
obj-$(CONFIG_LED_RTL8197DL)	+= led_rtl8197dl.o
obj-$(CONFIG_LED_C1000)		+= led_c1k.o