EXTRA_CFLAGS = -Idrivers/net/wireless/MT7612E/rlt_wifi/include \
				-Idrivers/net/wireless/MT7612E/rlt_wifi/ate/include

DRV_NAME = rlt_wifi
RT_WIFI_DIR = ../rlt_wifi

obj-m += rlt_wifi.o
rlt_wifi-objs := rlt_wifi.mod.o

