
# Button Core
obj-$(CONFIG_TBS_BUTTON)	+= btn-core.o

# Button Platform Drivers
obj-$(CONFIG_BUTTON_AR7130)	+= btn_ar7130.o
obj-$(CONFIG_BUTTON_AMAZON_SE)	+= btn_amazon_se.o
obj-$(CONFIG_BUTTON_RT3052)	+= btn_rt3052.o
obj-$(CONFIG_BUTTON_VX180)	+= btn_vx180.o
obj-$(CONFIG_BUTTON_RTL8672)	+= btn_rtl8672.o
obj-$(CONFIG_BUTTON_RTL8196C)	+= btn_rtl8196c.o
obj-$(CONFIG_BUTTON_RTL8196E)	+= btn_rtl8196e.o
obj-$(CONFIG_BUTTON_C1000)	+= btn_c1k.o
obj-$(CONFIG_BUTTON_C1000_INT)	+= btn_c1k_int.o
obj-$(CONFIG_BUTTON_RTL8197D)   += btn_rtl8197d.o
obj-$(CONFIG_BUTTON_RTL8197DL)   += btn_rtl8197dl.o
