/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux localhost.localdomain 2.6.18-53.el5 #1 SMP Mon Nov 12 02:22:48 EST 2007 i686 i686 i386 GNU/Linux"
#define BUILD_ENV_DATE "2011年 12月 03日 星期六 10:02:52 CST"
#define BUILD_ENV_SRCDIR "/home/wyb/wyb/marvell/trunk/src/opensource/samba/samba-3.0.2/source"
#define BUILD_ENV_BUILDDIR "/home/wyb/wyb/marvell/trunk/src/opensource/samba/samba-3.0.2/source"
#define BUILD_ENV_USER "root"
#define BUILD_ENV_HOST "localhost.localdomain"
#define BUILD_ENV_COMPILER "/opt/tbs_toolchains/marvell_uclibc/usr/bin/arm-linux-gcc"
#endif /* _BUILD_ENV_H */
